version: "3.1"

services: 
  server1: 
    image: node-app
    expose:
      - "3000"
    environment: 
      PORT: 3000
  server2:
    image: node-app
    expose:
      - "3001"
    environment: 
      PORT: 3001
  server3:
    image: node-app
    expose:
      - "3002"
    environment: 
      PORT: 3002
  nginx: 
    image: nginx-conf2
    ports:
      - 8080:80
    depends_on:
      - server1
      - server2
      - server3
  